### PR TITLE
[WIP] ScriptGen implementation

### PR DESCRIPTION
**Pull request by mholo65**
WIP...

### CODE REVIEW

**Comment by mholo65** [comment]
ping @patriksvensson 

This is the start of generating whole scripts...

Just some questions? Should server also perform download of addins/tools? Might be difficult since `Cake.NuGet` isnt available...

**Comment by patriksvensson** [comment]
@mholo65 Hmm. I'm not sure. Perhaps we should wait with downloading of nuget and similar until later.

**Comment by mholo65** [comment]
Yeah, we could return list of NuGet references as part of the CakeScript result. Then it's up to the calling application to download them and rerun scriptgen.

Or better yet, provide this as a callback mechanism. IMO, it's the calling applications responsibility to download dependencies.

**Comment by patriksvensson** [comment]
@mholo65 Yes, I think that is a good idea. Since #load, #tool and #addin are pluggable, it's impossible for the Cake server to know what to process unless the calling application tells it what to process. I'm in favor of making Bakery as stupid as possible.

**Comment by mholo65** [comment]
Agreed! :+1: Bakery should be as stupid as possible!

**Comment by patriksvensson** [comment]
Like me! 😸

**Pull request merged**
